export function buildMermaidDiagramConfig() {
  return {
    flowchart: {
      useMaxWidth: true,
      htmlLabels: true,
      curve: 'basis',
      padding: 16,
      nodeSpacing: 60,
      rankSpacing: 60,
      diagramPadding: 16,
      defaultRenderer: 'dagre-wrapper',
      wrappingWidth: 200,
    },
    sequence: {
      diagramMarginX: 40,
      diagramMarginY: 16,
      actorMargin: 60,
      width: 160,
      height: 60,
      boxMargin: 12,
      boxTextMargin: 8,
      noteMargin: 12,
      messageMargin: 40,
      mirrorActors: true,
      bottomMarginAdj: 1,
      useMaxWidth: true,
      rightAngles: false,
      showSequenceNumbers: false,
      wrap: true,
      wrapPadding: 12,
    },
    gantt: {
      titleTopMargin: 20,
      barHeight: 24,
      barGap: 6,
      topPadding: 40,
      leftPadding: 80,
      gridLineStartPadding: 40,
      fontSize: 12,
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      numberSectionStyles: 4,
      useWidth: 960,
    },
    pie: {
      useWidth: 600,
      useMaxWidth: true,
      textPosition: 0.75,
    },
    state: {
      dividerMargin: 12,
      sizeUnit: 8,
      padding: 10,
      textHeight: 12,
      titleShift: -20,
      noteMargin: 12,
      forkWidth: 80,
      forkHeight: 8,
      miniPadding: 4,
      fontSizeFactor: 5.02,
      fontSize: 20,
      labelHeight: 20,
      edgeLengthFactor: '24',
      compositTitleSize: 40,
      radius: 6,
      defaultRenderer: 'dagre-wrapper',
    },
    class: {
      useMaxWidth: true,
      defaultRenderer: 'dagre-wrapper',
    },
    er: {
      diagramPadding: 24,
      layoutDirection: 'TB',
      minEntityWidth: 120,
      minEntityHeight: 80,
      entityPadding: 16,
      stroke: 'gray',
      fill: 'honeydew',
      fontSize: 13,
      useMaxWidth: true,
    },
    gitGraph: {
      showBranches: true,
      showCommitLabel: true,
      mainBranchName: 'main',
      mainBranchOrder: 0,
      rotateCommitLabel: true,
    },
  };
}
